//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.05 at 02:29:03 PM BST 
//


package uk.co.britishgas.bertha;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.co.britishgas.bertha package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClassesElements_QNAME = new QName("urn:britishgas.co.uk:Bertha", "ClassesElements");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.co.britishgas.bertha
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link Classes }
     * 
     */
    public Classes createClasses() {
        return new Classes();
    }

    /**
     * Create an instance of {@link Class }
     * 
     */
    public Class createClass() {
        return new Class();
    }

    /**
     * Create an instance of {@link CollectionColumns }
     * 
     */
    public CollectionColumns createCollectionColumns() {
        return new CollectionColumns();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Classes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:britishgas.co.uk:Bertha", name = "ClassesElements")
    public JAXBElement<Classes> createClassesElements(Classes value) {
        return new JAXBElement<Classes>(_ClassesElements_QNAME, Classes.class, null, value);
    }

}
