//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.05 at 02:29:03 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:britishgas.co.uk:Bertha")
package uk.co.britishgas.bertha;
